# Example sentinel.conf can be downloaded from http://download.redis.io/redis-stable/sentinel.conf
version: "3"
services:
  sentinel1:
    image: redis:latest
    container_name: redis-sentinel-1
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
    - "26379:26379"
    volumes:
    - "/home/hy/foodie/redis/compose/sentinel/sentinel1.conf:/usr/local/etc/redis/sentinel.conf"
  sentinel2:
    image: redis:latest
    container_name: redis-sentinel-2
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
    - "26380:26379"
    volumes:
    - "/home/hy/foodie/redis/compose/sentinel/sentinel2.conf:/usr/local/etc/redis/sentinel.conf"
  sentinel3:
    image: redis:latest
    container_name: redis-sentinel-3
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
    - "26381:26379"
    volumes:
    - "/home/hy/foodie/redis/compose/sentinel/sentinel3.conf:/usr/local/etc/redis/sentinel.conf"
networks:
  default:
    external:
      name: "master-slave_sentinel-master"