server:
  port: 8033
spring:
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver          # mysql驱动
    url: jdbc:mysql://192.168.7.194:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456
  data:
    elasticsearch:
      cluster-nodes: 192.168.7.194:9300
      cluster-name: docker-cluster
      repositories:
        enabled: true
#  elasticsearch:
#    rest:
#      uris: https://192.168.7.194:9200

  redis:
    #单机实例方式
    #    host: 192.168.7.194
    #    port: 6379
    #    database: 1

    # redis主从哨兵模式
    database: 1
    password: 123456
    sentinel:
      master: mymaster
      nodes: 192.168.7.194:26379,192.168.7.194:26380,192.168.7.194:26381